service: my-service

frameworkVersion: "3"

plugins:
  - serverless-rust
  - serverless-offline

provider:
  name: aws
  runtime: rust
  stage: dev

package:
  individually: true

custom:
  rust:
    dockerless: true

functions:
  base_http:
    handler: base_http
    events:
      - http:
          method: get
          path: health