name: CICD
on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install build essential for ssl
        run: |
          sudo apt-get install -y curl build-essential

      - name: Cross build with all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true 
          command: build
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose

  ci:
    name: Continuous Integration
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cargo Lambda Watch
        run: |
          cargo lambda watch &
      - name: Cross build with all features
        uses: actions-rs/cargo@v1
        with:
          use-cross: true 
          command: test
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose -- --test-threads=1
