name: CICD
on:
  push:
#    branches:
#      - 'main'
#      - 'releases/**'
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2

#      - name: Install stable toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true

#      - name: Cross build with all features
#        uses: actions-rs/cargo@v1
#        with:
#          use-cross: true 
#          command: build
#          args: --release --target x86_64-unknown-linux-musl --all-features --verbose

  ci:
    name: Continuous Integration
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo lambda install
        run: |
          cargo install cargo-lambda

      - name: Cargo lambda watch
        run: |
          cargo lambda watch &

      - name: Cross test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true 
          command: test
          args: --release --target x86_64-unknown-linux-musl --all-features --verbose
