name: CICD
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true

  #     - name: Cross build with all features
  #       uses: actions-rs/cargo@v1
  #       with:
  #         use-cross: true 
  #         command: build
  #         args: --release --all-features --verbose

  #    # - name: Setup Cargo Lambda
  #    #   uses: zerj9/setup-cargo-lambda@v0.1.0

  #    # - name: Setup Zig
  #    #   uses: goto-bus-stop/setup-zig@v1.3.0

  #    # - name: Cargo lambda build
  #    #   run: |
  #    #     cargo lambda build --output-format zip --release

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display current directory
        run: |
          mysqld --version
          echo "DATABASE_URL=mysql://root:${{secrets.DATABASE_PASSWORD}}@127.0.0.1/test_db" >> .env
          pwd
          ls -al
          cat .env
          echo "${{secrets.DATABASE_PASSWORD}}"

      # - name: Shutdown Ubuntu MySQL (SUDO)
      #   run: |
      #     sudo systemctl restart mysql
      #     sudo systemctl stop mysql

      # 1を試しているため不要
      # - name: Display MySQL mysql.user
      #   run: |
      #     sudo systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
      #     sudo systemctl start mysql
      #     sudo systemctl status mysql
      #     sudo mysql -uroot -e="SELECT user, host FROM mysql.user"

      # 1
      - name: MySQL起動
        run: |
          sudo service mysqld start

      # No such file or directoryが出るためコメントアウト
      # - name: Display MySQL initial password
      #   run: |
      #     cat /var/log/mysqld.log | sudo grep password

      - name: MySQL sock file exists check
        run: |
          sudo mkdir -p /var/run/mysqld/
          sudo touch /var/run/mysqld/mysqld.sock

      - name: MySQL alive check with ping
        run: mysqladmin ping -uroot -p${{ secrets.DATABASE_PASSWORD }}
      - if: failure()
        name: A
        run: mysqladmin ping -uroot -p${{ secrets.DATABASE_ROOT_PASSWORD }}
      - name: B
        if: failure()
        run: mysqladmin ping -uroot
      - if: failure()
        run: sudo mysqladmin ping -uroot -p${{ secrets.DATABASE_PASSWORD }}
      - if: failure()
        run: sudo mysqladmin ping -uroot -p${{ secrets.DATABASE_ROOT_PASSWORD }}
      - if: failure()
        run: sudo mysqladmin ping -uroot

      # ファイルが存在しないためコメントアウト
      # - name: MySQL sock file exists check
      #   run: |
      #     test -f /var/run/mysqld/mysqld.sock

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sqlx-cli
        run: |
          cargo install sqlx-cli

      - name: Database setup
        run: |
          sqlx database create

      - name: Database migrate
        run: |
          sqlx migrate run

      - name: Setup Cargo Lambda
        uses: zerj9/setup-cargo-lambda@v0.1.0

      - name: Install cargo watch
        run: |
          cargo install cargo-watch

      - name: Cargo lambda watch, invoke and cargo test
        run: |
          cargo lambda watch &
          sleep 1
          curl -L http://localhost:9000/lambda-url/lambda_function_01
          cargo lambda invoke lambda_function_01 --data-ascii "{}"
          cargo test -- --test-threads=1

      - name: Clean up some process
        run: |
          ps aux | grep "watch" | grep -v grep | awk '{ print "kill -9", $2 }' | sudo sh